//This Enum can be extended from backend error enum
export enum Errors {
  SET_SECRE_STORE = 'SET_SECRE_STORE',
  ALREADY_EXISITED = 'ALREADY_EXISITED',
  SERVER_ERROR = 'SERVER_ERROR',
  ALL_FIELDS_REQUIRED = 'ALL_FIELDS_REQUIRED',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  COUNTRY_IS_REQUIRED = 'COUNTRY_IS_REQUIRED',
}
